function [fitresult, gof] = TireTemperaturecreateFit(ET_out, FY_out)
%CREATEFIT(ET_OUT,FY_OUT)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : ET_out
%      Y Output: FY_out
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 28-Oct-2019 00:48:23


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( ET_out, FY_out );

% Set up fittype and options.
ft = fittype( 'rat22' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Normalize = 'on';
opts.StartPoint = [0.0770994528704891 0.838167021806211 0.417734516108821 0.240824534733949 0.896446367435336];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'FY_out vs. ET_out', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel ET_out
ylabel FY_out
grid on


