function [fitresult, gof] = createFit(pseudo_lat_accel2, steer_angle2)
%CREATEFIT(PSEUDO_LAT_ACCEL2,STEER_ANGLE2)
%  Create a fit.
%
%  Data for 'Run1fit' fit:
%      X Input : pseudo_lat_accel2
%      Y Output: steer_angle2
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 10-Sep-2018 16:59:00


%% Fit: 'Run1fit'.
[xData, yData] = prepareCurveData( pseudo_lat_accel2, steer_angle2 );

% Set up fittype and options.
ft = fittype( 'power2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [12.9315258381431 0.121943183436906 -0.00813571951098755];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Run1fit' );
h = plot( fitresult, xData, yData );
legend( h, 'Raw Data', 'Power Fit', 'Location', 'NorthEast' );
% Label axes
xlabel('Lateral Acceleration (g)')
ylabel('Steering Angle (deg)')
grid on

understeer_gradient = differentiate(fitresult,xData);

% Plot fit with data.
figure( 'Name', 'Run1fit' );
h = plot(xData,understeer_gradient);
% Label axes
xlabel('Lateral Acceleration (g)')
ylabel('Understeer Gradient (deg/g)')

